/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:e1289b66-7d72-4060-b2a2-11e1556eb6c3",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_vMY0gHNUf",
    "aws_user_pools_web_client_id": "2rsuh6sq3ks5lk1ks1aijbrvsr",
    "oauth": {}
};


export default awsmobile;
